apiVersion: v1

kind: Service
metadata:
  name: {{ .Release.Name }}-tensorflow-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8888
  selector:
    app: {{ .Release.Name }}-tensorflow
